POST http://localhost:8080/setConfig
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}

###

POST http://localhost:8080/test
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}

###

POST http://localhost:8080/reset
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}