POST http://localhost:8080/setConfig
content-type: application/json

{
  "url": "http://45.8.228.5:7070/test",
  "method": "GET",
  "rps": 600,
  "testing_duration": 30
}

###

POST http://localhost:8080/test
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}

###

GET http://localhost:8000/reset
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}


###
POST http://45.8.228.5:7070/test
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}

###

POST http://45.8.228.5:7070/reset
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}