apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: monitoring
spec:
  storageClassName: nfs-storage
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi