apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: 'container_cpu_usage_seconds_total{namespace!="", pod!=""}'
      resources:
        overrides:
          namespace: 
            resource: namespace
          pod: 
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_by_artem"
      metricsQuery: 'sum (rate (container_cpu_usage_seconds_total{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>) * 100'