FROM golang:1.17-alpine3.13 as build

ENV GOOS linux

ENV CGO_ENABLED 0

WORKDIR /app

RUN go mod init testserver

COPY . .

RUN go build -o app testserver.go



FROM alpine:3.14 as production

RUN apk add --no-cache ca-certificates

COPY --from=build app .

EXPOSE 8080

CMD ./app
