apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: overload
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
    matchExpressions: 
      - key: app
        operator: In
        values:
          - overload
  template:
    metadata:
      labels:
        creation_method: replicaSet
        env: prod
        app: overload
    spec:
      nodeSelector:
        nodeType: prod
      containers:
      - image: artemchikus/overload:overload
        imagePullPolicy: Always
        name: overload-rs
        ports: 
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet: 
            path: /alive
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10